### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by steveharoz** [journalovi/jovi_template#3]
Instead of numbers, use a more readable format. APA is an example format, but anything with names and years is fine.

(Last_name, Year)
(Last_name1 & Last_name2, Year)
(Last_name1, Last_name2, & Last_name3, Year)
(Last_name1, Last_name2, Last_name3, et al, Year)
As was described in Last_name1 & Last_name2 (Year), ...

**Comment by mjskay** [comment]
This works now
