### ISSUE TITLE
Numbered section headers

### ISSUE THREAD

**Issue by steveharoz** [journalovi/jovi_template#4]

**Comment by mjskay** [comment]
What's the motivation for numbers? Internal references? Those can easily be done with anchored links in a webpage.

**Comment by steveharoz** [comment]
1. Keeping track of where you are in document. "Are these the results for experiment 2 or 3?" A table of contents that stays on the screen may accomplish that goal for desktops, but mobile reading requires a lot of scrolling, which makes it easy to get lost.

2. Referencing part of the article externally such as in a review, comment, or validation report. "The interaction effect reported in section 4.2..." Usually, page number are used for this.

**Comment by mjskay** [comment]
Fair. I will play around with something subtle for this.
